# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IuBugTracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vender_id', models.IntegerField(verbose_name='厂商id')),
                ('device_id', models.IntegerField(verbose_name='设备id')),
                ('serial', models.CharField(max_length=255, verbose_name='设备串号')),
                ('android_device_unique_id', models.CharField(max_length=255, verbose_name='安卓设备唯一编号')),
                ('android_user_unique_id', models.IntegerField(verbose_name='使用用户的唯一id编号')),
                ('android_device_info', models.IntegerField(verbose_name='Build.BRAND + Build.DEVICE + Build.MODEL')),
                ('android_os_ver', models.IntegerField(verbose_name='操作系统版本')),
                ('lib_version', models.IntegerField(verbose_name='所使用的库的版本')),
                ('sync_trigger_mode', models.IntegerField(null=True, verbose_name='所使用的同步触发模式')),
                ('sync_mode', models.IntegerField(null=True, verbose_name='同步模式')),
                ('sync_record_mode', models.IntegerField(null=True, verbose_name='同步记录模式')),
                ('exception', models.TextField(null=True, verbose_name='异常名称')),
                ('traceback', models.TextField(null=True, verbose_name='调用堆栈')),
                ('fileinfo', models.TextField(null=True, verbose_name='文件信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='IuDeviceInfoTracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=255, verbose_name='设备串号')),
                ('android_device_unique_id', models.CharField(max_length=255, verbose_name='安卓设备唯一编号')),
                ('android_user_unique_id', models.IntegerField(verbose_name='使用用户的唯一id编号')),
                ('android_device_info', models.IntegerField(verbose_name='Build.BRAND + Build.DEVICE + Build.MODEL')),
                ('android_os_ver', models.IntegerField(verbose_name='操作系统版本')),
                ('device_info', models.TextField(verbose_name='设备信息')),
            ],
        ),
        migrations.CreateModel(
            name='IuPerfTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender_id', models.IntegerField(verbose_name='厂商id')),
                ('device_id', models.IntegerField(verbose_name='设备id')),
                ('serial', models.CharField(max_length=255, verbose_name='设备串号')),
                ('android_device_unique_id', models.CharField(max_length=255, verbose_name='安卓设备唯一编号')),
                ('android_user_unique_id', models.IntegerField(verbose_name='使用用户的唯一id编号')),
                ('android_device_info', models.IntegerField(verbose_name='Build.BRAND + Build.DEVICE + Build.MODEL')),
                ('android_os_ver', models.IntegerField(verbose_name='操作系统版本')),
                ('lib_version', models.IntegerField(verbose_name='所使用的库的版本')),
                ('sync_trigger_mode', models.IntegerField(verbose_name='所使用的同步触发模式')),
                ('sync_mode', models.IntegerField(verbose_name='同步模式')),
                ('sync_record_mode', models.IntegerField(verbose_name='同步记录模式')),
                ('filesize', models.IntegerField(verbose_name='传输文件尺寸')),
                ('start_ts', models.FloatField(verbose_name='开始时间')),
                ('end_ts', models.FloatField(verbose_name='结束时间')),
                ('cost_ts', models.FloatField(verbose_name='消耗时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
