# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_upload_tracker_api', '0002_auto_20170820_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iuperftracker',
            name='android_device_info',
            field=models.CharField(max_length=255, verbose_name='Build.BRAND + Build.DEVICE + Build.MODEL'),
        ),
    ]
