# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_upload_tracker_api', '0004_auto_20170909_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iubugtracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iudeviceinfotracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
